name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # Step that does that actual cache save and restore
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: set maven version
        if: startsWith(github.ref, 'refs/tags/')
        run: mvn versions:set -DnewVersion=${GITHUB_REF:10}
      - name: Build with Maven
        run: mvn package
      - shell: bash
        run: |
          cp target/trambient*with-dependencies.jar trambient.jar
      - name: Upload maven jar
        uses: actions/upload-artifact@v2
        with:
          name: maven-jar
          path: trambient.jar
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download jar
        uses: actions/download-artifact@v2
        with:
          name: maven-jar
      - name: trim changes from changelog
        shell: bash
          run: |
            cp CHANGELOG.md changes.md
            sed -i '/## /,$!d' changes.md
            sed -i 1d changes.md
            sed -i '/^## /q;' changes.md
            sed -i '$ d' changes.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: changes.md
          files: |
            CHANGELOG.md
            LICENSE
            trambient.jar